[build]
output_dir = "exe"
build_dir = "D:\\c"
msix_output_dir = "D:\\c\\msix"
distribution_name = "psage"

[project]
main_script = "cli.py"
main_module_name = "psage"
root_globs = ["*.py"]

[sources]
packages = []
